# Generated by Django 4.1.6 on 2023-03-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='product_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
